#!/bin/sh

gitrev=`git rev-parse HEAD`

cat >gipaw_version.f90 <<EOF
!
! Copyright (C) 2003-2013 Quantum ESPRESSO group
! This file is distributed under the terms of the
! GNU General Public License. See the file \`License'
! in the root directory of the present distribution,
! or http://www.gnu.org/copyleft/gpl.txt .
!

! NOTE: this file is automatically created

!----------------------------------------------------------------------------
MODULE gipaw_version
  !
  IMPLICIT NONE
  !
  SAVE
  !
  CHARACTER (LEN=40) :: gipaw_git_revision = "$gitrev"
  !
END MODULE gipaw_version
EOF

