












! DO NOT EDIT xml_routines.f90, EDIT INSTEAD xml_routines.f90.in
! m4 xmlmacros.m4 xml_routines.f90.in >xml_routines.f90 

!
! Copyright (C) 2001-2021 Quantum ESPRESSO group
! This file is distributed under the terms of the
! GNU General Public License. See the file License
! in the root directory of the present distribution,
! or http://www.gnu.org/copyleft/gpl.txt .
!

! XML routines non relying on qexsd. For a small code such as
! GIPAW, qexsd is an overkill. Here I use the FoX library directly
! to input and output XML files

! commodity macros
#define CHECK_IONODE if (.not. ionode) return

!-----------------------------------------------------------------------
MODULE xml_routines
!-----------------------------------------------------------------------  
  ! ... This module contains the variables routines to I/O the XML files
  USE kinds,                       ONLY : dp
  USE io_global,                   ONLY : ionode
  USE wxml                         ! to output XML
  USE dom                          ! to parse XML file

  IMPLICIT NONE
  SAVE
  
  type(xmlf_t) :: xmlf             ! xml file handle

  character(5),  parameter :: fmt_name = "QEXSD"
  character(8),  parameter :: fmt_version = "21.07.16"

  PUBLIC :: open_xml_output, close_xml_output
  PUBLIC :: xml_output_generalinfo, xml_output_parallelinfo
  PUBLIC :: xml_output_namelist, xml_output_results
  PUBLIC :: xml_output_status
  PUBLIC :: xml_output_timinginfo
  PUBLIC :: xml_output_closed

  CONTAINS

  !-----------------------------------------------------------------------
  SUBROUTINE open_xml_output(filename)
  !-----------------------------------------------------------------------
    implicit none
    character(len=*), intent(in) :: filename
    integer :: ierr

    CHECK_IONODE
    call XML_OpenFile(filename, xmlf, replace=.true., pretty_print=.true., namespace=.true., iostat=ierr)
    !if ierr

    ! write namespace
    call XML_DeclareNamespace(xmlf, prefix="xsi", nsURI="http://www.w3.org/2001/XMLSchema-instance")
    call XML_DeclareNamespace(xmlf, prefix="qes", nsURI="http://www.quantum-espresso.org/ns/qes/qes-1.0")
    call XML_DeclareNamespace(xmlf, prefix="gpw", nsURI="http://www.quantum-espresso.org/ns/gpw/qes_gipaw_1.0")
    call XML_NewElement(xmlf, name="gpw:gipaw")
    call XML_AddAttribute(xmlf, name="xsi:schemaLocation", &
                          value="http://www.quantum-espresso.org/ns/gpw/qes_gipaw_1.0 "//&
                                "http://www.quantum-espresso.org/ns/gpw/gpw_202201.xsd")
  END SUBROUTINE open_xml_output


  !-----------------------------------------------------------------------
  SUBROUTINE close_xml_output
  !-----------------------------------------------------------------------
    implicit none
   
    CHECK_IONODE
    call XML_Close(xmlf, empty=.false.)

  END SUBROUTINE close_xml_output


  !-----------------------------------------------------------------------
  SUBROUTINE xml_output_generalinfo
  !-----------------------------------------------------------------------
    USE gipaw_version
    implicit none
    character(9) :: cdate, ctime
    character(60) :: timestamp

    call date_and_tim(cdate, ctime)
    timestamp = 'This run was terminated on:  ' // ctime // ' ' // cdate(1:2) // ' '//cdate(3:5) // ' '// cdate (6:9)

    CHECK_IONODE
    call XML_NewElement(xmlf, "general_info")
      call XML_NewElement(xmlf, "xml_format")
        call XML_AddAttribute(xmlf, "NAME", fmt_name)
        call XML_AddAttribute(xmlf, "VERSION", fmt_version)
        call XML_AddCharacters(xmlf, fmt_name//'_'//fmt_version)
      call XML_EndElement(xmlf, "xml_format")
      call XML_NewElement(xmlf, "creator")
        call XML_AddAttribute(xmlf, "NAME", 'GIPAW')
        call XML_AddAttribute(xmlf, "VERSION", gipaw_git_revision)
        call XML_AddCharacters(xmlf, 'XML file generated by GIPAW')
      call XML_EndElement(xmlf, "creator")
      call XML_NewElement(xmlf, "created")
        call XML_AddAttribute(xmlf, "DATE", cdate)
        call XML_AddAttribute(xmlf, "TIME", ctime)
        call XML_AddCharacters(xmlf, trim(timestamp))
      call XML_EndElement(xmlf, "created")
      call XML_NewElement(xmlf, "job")
      call XML_EndElement(xmlf, "job")
    call XML_EndElement(xmlf, "general_info")

  END SUBROUTINE xml_output_generalinfo


  !-----------------------------------------------------------------------
  SUBROUTINE xml_output_parallelinfo
  !-----------------------------------------------------------------------
    USE mp_world,         ONLY : nproc
    USE mp_pools,         ONLY : npool
    USE mp_bands,         ONLY : ntask_groups, nbgrp
    USE laxlib_processors_grid, ONLY : nproc_ortho
    implicit none
    integer :: nthreads=1
#if defined(__OMP) 
    integer, external :: omp_get_max
    nthreads = omp_get_max()
#endif      

    CHECK_IONODE
    call XML_NewElement(xmlf, "parallel_info")
      call XML_NewElement(xmlf, "nprocs")
        call XML_AddCharacters(xmlf, nproc)
      call XML_EndElement(xmlf, "nprocs")
      call XML_NewElement(xmlf, "nthreads")
	call XML_AddCharacters(xmlf, nthreads)
	call XML_EndElement(xmlf, "nthreads")
      call XML_NewElement(xmlf, "ntasks")
        call XML_AddCharacters(xmlf, ntask_groups)
      call XML_EndElement(xmlf, "ntasks")
      call XML_NewElement(xmlf, "nbgrp")
	call XML_AddCharacters(xmlf, nbgrp)
	call XML_EndElement(xmlf, "nbgrp")
      call XML_NewElement(xmlf, "npool")
	call XML_AddCharacters(xmlf, npool)
	call XML_EndElement(xmlf, "npool")
      call XML_NewElement(xmlf, "ndiag")
        call XML_AddCharacters(xmlf, nproc_ortho)
      call XML_EndElement(xmlf, "ndiag")
    call XML_EndElement(xmlf, "parallel_info")

  END SUBROUTINE xml_output_parallelinfo


  !-----------------------------------------------------------------------
  SUBROUTINE xml_output_namelist
  !-----------------------------------------------------------------------
    USE io_files,        ONLY : prefix, tmp_dir
    USE cell_base,       ONLY : tpiba
    USE ions_base,       ONLY : nat
    USE gipaw_module     ! to access internal variables
    implicit none

    CHECK_IONODE
    call XML_NewElement(xmlf, "input")
      call XML_NewElement(xmlf, "job")
	call XML_AddCharacters(xmlf, trim(job))
	call XML_EndElement(xmlf, "job")
      call XML_NewElement(xmlf, "prefix")
	call XML_AddCharacters(xmlf, trim(prefix))
	call XML_EndElement(xmlf, "prefix")
      call XML_NewElement(xmlf, "tmp_dir")
	call XML_AddCharacters(xmlf, trim(tmp_dir))
	call XML_EndElement(xmlf, "tmp_dir")
      call XML_NewElement(xmlf, "conv_threshold")
	call XML_AddCharacters(xmlf, conv_threshold)
	call XML_EndElement(xmlf, "conv_threshold")
      call XML_NewElement(xmlf, "restart_mode")
	call XML_AddCharacters(xmlf, trim(restart_mode))
	call XML_EndElement(xmlf, "restart_mode")
      call XML_NewElement(xmlf, "q_gipaw")
        call XML_AddCharacters(xmlf, q_gipaw*tpiba)
      call XML_EndElement(xmlf, "q_gipaw")
      call XML_NewElement(xmlf, "verbosity")
	call XML_AddCharacters(xmlf, trim(verbosity))
	call XML_EndElement(xmlf, "verbosity")
      call XML_NewElement(xmlf, "filcurr")
	call XML_AddCharacters(xmlf, trim(filcurr))
	call XML_EndElement(xmlf, "filcurr")
      call XML_NewElement(xmlf, "filfield")
	call XML_AddCharacters(xmlf, trim(filfield))
	call XML_EndElement(xmlf, "filfield")
      call XML_NewElement(xmlf, "filnics")
	call XML_AddCharacters(xmlf, trim(filnics))
	call XML_EndElement(xmlf, "filnics")
      call XML_NewElement(xmlf, "pawproj")
	call XML_AddCharacters(xmlf, pawproj)
	call XML_EndElement(xmlf, "pawproj")
      call XML_NewElement(xmlf, "use_nmr_macroscopic_shape")
	call XML_AddCharacters(xmlf, use_nmr_macroscopic_shape)
	call XML_EndElement(xmlf, "use_nmr_macroscopic_shape")
      call XML_NewElement(xmlf, "nmr_macroscopic_shape")
        call XML_AddAttribute(xmlf, "rank", "2")
        call XML_AddAttribute(xmlf, "dims", "3 3")
        call XML_AddCharacters(xmlf, nmr_macroscopic_shape)
      call XML_EndElement(xmlf, "nmr_macroscopic_shape")
      call XML_NewElement(xmlf, "spline_ps")
	call XML_AddCharacters(xmlf, spline_ps)
	call XML_EndElement(xmlf, "spline_ps")
      call XML_NewElement(xmlf, "diagonalization")
	call XML_AddCharacters(xmlf, trim(diagonalization))
	call XML_EndElement(xmlf, "diagonalization")
      call XML_NewElement(xmlf, "q_efg")
        call XML_AddAttribute(xmlf, "size", nat)
        call XML_AddCharacters(xmlf, q_efg)
      call XML_EndElement(xmlf, "q_efg")
      call XML_NewElement(xmlf, "max_seconds")
	call XML_AddCharacters(xmlf, max_seconds)
	call XML_EndElement(xmlf, "max_seconds")
      call XML_NewElement(xmlf, "r_rand")
	call XML_AddCharacters(xmlf, r_rand)
	call XML_EndElement(xmlf, "r_rand")
      call XML_NewElement(xmlf, "hfi_output_unit")
	call XML_AddCharacters(xmlf, trim(hfi_output_unit))
	call XML_EndElement(xmlf, "hfi_output_unit")
      call XML_NewElement(xmlf, "hfi_nuclear_g_factor")
        call XML_AddAttribute(xmlf, "size", nat)
        call XML_AddCharacters(xmlf, hfi_nuclear_g_factor)
      call XML_EndElement(xmlf, "hfi_nuclear_g_factor")
      call XML_NewElement(xmlf, "core_relax_method")
	call XML_AddCharacters(xmlf, core_relax_method)
	call XML_EndElement(xmlf, "core_relax_method")
      call XML_NewElement(xmlf, "hfi_via_reconstruction_only")
	call XML_AddCharacters(xmlf, hfi_via_reconstruction_only)
	call XML_EndElement(xmlf, "hfi_via_reconstruction_only")
    call XML_EndElement(xmlf, "input")
  END SUBROUTINE xml_output_namelist


  !-----------------------------------------------------------------------
  SUBROUTINE xml_output_susceptibility
  !-----------------------------------------------------------------------
    USE gipaw_results
    implicit none

    CHECK_IONODE

    call XML_NewElement(xmlf, "susceptibility_low")
      call XML_AddAttribute(xmlf, "rank", '2')
      call XML_AddAttribute(xmlf, "dims", '3 3')
      call XML_AddCharacters(xmlf, res_suscept1)
    call XML_EndElement(xmlf, "susceptibility_low")

    call XML_NewElement(xmlf, "susceptibility_high")
      call XML_AddAttribute(xmlf, "rank", '2')
      call XML_AddAttribute(xmlf, "dims", '3 3')
      call XML_AddCharacters(xmlf, res_suscept2)
    call XML_EndElement(xmlf, "susceptibility_high")

  END SUBROUTINE xml_output_susceptibility


  !-----------------------------------------------------------------------
  SUBROUTINE xml_atom_attributes(na, units, rank, dims)
  !-----------------------------------------------------------------------
    USE gipaw_results
    USE ions_base, ONLY: tau, atm, ityp
    implicit none
    integer, intent(in) :: na
    character(*) :: rank, dims, units

    call XML_AddAttribute(xmlf, "name", trim(atm(ityp(na))))
    call XML_AddAttribute(xmlf, "tau", tau(:,na))
    call XML_AddAttribute(xmlf, "index", na)
    call XML_AddAttribute(xmlf, "rank", rank)
    call XML_AddAttribute(xmlf, "dims", dims)
    call XML_AddAttribute(xmlf, "units", units)

  END SUBROUTINE xml_atom_attributes


  !-----------------------------------------------------------------------
  SUBROUTINE xml_output_results
  !-----------------------------------------------------------------------
    USE gipaw_module     ! to access internal variables
    USE gipaw_results
    USE ions_base, ONLY: nat
    implicit none
    integer :: na

    CHECK_IONODE
    call XML_NewElement(xmlf, "output")

!!    if (job == 'nmr') then
      call xml_output_susceptibility
      call XML_NewElement(xmlf, "shielding_tensors")
      do na = 1, nat
        call XML_NewElement(xmlf, "atom")
          call xml_atom_attributes(na, 'ppm', '2', '3 3')
          call XML_AddCharacters(xmlf, res_nmr_sigma(:,:,na))
        call XML_EndElement(xmlf, "atom")
      enddo
      call XML_EndElement(xmlf, "shielding_tensors")
!!    endif

!!    if (job == 'g_tensor') then
!!      call xml_output_susceptibility
      call XML_NewElement(xmlf, "delta_g")
        call XML_AddAttribute(xmlf, "rank", '2')
        call XML_AddAttribute(xmlf, "dims", '3 3')
        call XML_AddCharacters(xmlf, res_epr_deltag)
      call XML_EndElement(xmlf, "delta_g")
      call XML_NewElement(xmlf, "delta_g_paratec")
        call XML_AddAttribute(xmlf, "rank", '2')
        call XML_AddAttribute(xmlf, "dims", '3 3')
        call XML_AddCharacters(xmlf, res_epr_deltag_paratec)
      call XML_EndElement(xmlf, "delta_g_paratec")
!!    endif

!!    if (job == 'efg') then
      call XML_NewElement(xmlf, "electric_field_gradients")
        do na = 1, nat
          call XML_NewElement(xmlf, "atom")
            call xml_atom_attributes(na, 'MHz', '2', '3 3')
            call XML_AddCharacters(xmlf, res_efg(:,:,na))
          call XML_EndElement(xmlf, "atom")
        enddo
        call XML_EndElement(xmlf, "electric_field_gradients")
!!    endif

!!    if (job == 'hyperfine') then
      call XML_NewElement(xmlf, "hyperfine_dipolar")
      do na = 1, nat
        call XML_NewElement(xmlf, "atom")
          call xml_atom_attributes(na, trim(hfi_output_unit), '2', '3 3')
          call XML_AddCharacters(xmlf, res_hfi_dip(:,:,na))
        call XML_EndElement(xmlf, "atom")
      enddo
      call XML_EndElement(xmlf, "hyperfine_dipolar")
      call XML_NewElement(xmlf, "hyperfine_fermi_contact")
      do na = 1, nat
        call XML_NewElement(xmlf, "atom")
          call xml_atom_attributes(na, trim(hfi_output_unit), '1', '1')
          call XML_AddCharacters(xmlf, res_hfi_fc(na))
        call XML_EndElement(xmlf, "atom")
      enddo
      call XML_EndElement(xmlf, "hyperfine_fermi_contact")
!!    endif

    call XML_EndElement(xmlf, "output")

  END SUBROUTINE xml_output_results


  !-----------------------------------------------------------------------
  SUBROUTINE xml_output_status
  !-----------------------------------------------------------------------
    implicit none
    integer :: exit_status = 0

    CHECK_IONODE
    call XML_NewElement(xmlf, "exit_status")
	call XML_AddCharacters(xmlf, exit_status)
	call XML_EndElement(xmlf, "exit_status")

  END SUBROUTINE xml_output_status


  !-----------------------------------------------------------------------
  SUBROUTINE xml_output_closed
  !-----------------------------------------------------------------------
    implicit none
    character(9) :: cdate, ctime

    CHECK_IONODE
    call date_and_tim(cdate, ctime)
    call XML_NewElement(xmlf, "closed")
       call XML_AddAttribute(xmlf, "DATE", cdate)
       call XML_AddAttribute(xmlf, "TIME", ctime)
    call XML_EndElement(xmlf, "closed")

  END SUBROUTINE xml_output_closed


  !-----------------------------------------------------------------------
  SUBROUTINE xml_output_timinginfo
  !-----------------------------------------------------------------------
    USE mytime,  ONLY : f_wall, f_tcpu
    USE gipaw_module
    implicit none
    real(dp), external :: get_clock
    real(dp) :: wall, cpu

    CHECK_IONODE
    call XML_NewElement(xmlf, "timing_info")
      call XML_NewElement(xmlf, "total")
        call XML_AddAttribute(xmlf, "label", 'GIPAW')
        cpu = f_tcpu()
        wall = f_wall()
        !wall = get_clock('GIPAW')
        call XML_NewElement(xmlf, "cpu")
	call XML_AddCharacters(xmlf, cpu)
	call XML_EndElement(xmlf, "cpu")
        call XML_NewElement(xmlf, "wall")
	call XML_AddCharacters(xmlf, wall)
	call XML_EndElement(xmlf, "wall")
      call XML_EndElement(xmlf, "total")

    call XML_EndElement(xmlf, "timing_info")

  END SUBROUTINE xml_output_timinginfo


END MODULE xml_routines

